version: '2'

services:
  hello:
    image: helloworld:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/app/prepare_env.sh", "flask", "run", "--host", "0.0.0.0"]
    ports:
      - "5000:5000"
